config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
  get 'sign_out', to: 'devise/sessions#destroy'
end
get 'folders/:folder_id/notes/search' => 'notes#search', as: "search_notepad"

  resources :folders do
    resources :notes
  end

  root 'folders#index'

  post 'folders/:folder_id/notes/new' => 'notes#create'
  post 'folders/:folder_id/notes/search' => 'notes#searchbutton'

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  validates :name, :desc, presence: true
  has_many :notepads, dependent: :destroy
  belongs_to :user
  default_scope -> {order(:id)}
  scope :visible, -> {where(visible:true)}
  scope :hidden, -> {where(visible:false)}

end

app/models/notepad.rb
class Notepad < ActiveRecord::Base
  validates :text, :url, presence: true
  belongs_to :folder
  def make_me_big
      self.text.upcase.reverse
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :folders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  # Forces a user that isn't logged in to login/sign up on all routes.
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    # .visible is NOT the visible parameter.
    # If the parameter 'visible' is true, then it will display all visible folders.
    # If 'visible' is false, then it will display all hidden folders.
    # current_user = User.first
    # current_user.folders
    if params[:visible] == "true"
      page = params[:page] || 1
      per = params[:per] || 50
      @folders = current_user.folders.visible.page(page).per(per)
    else
      @folders = current_user.folders.hidden
    end
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @folder = current_user.folders.find(params[:id])
    @notes = @folder.notepads
  end

  # GET /folders/new
  def new
    @folder = current_user.folders.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = current_user.folders.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_path, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = current_user.folders.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit!
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
   def index
     @notes = current_user.folders.find(params[:folder_id]).notepads
   end

   def searchbutton
    # redirect_to search_result_notepad_path(:text)
    # render text: "#{Notepad.where("text ilike ?", "%#{params[:quy]}%").inspect}"
    @folder = current_user.folders.find(params[:folder_id])
    @search = @folder.notepads.where("text ilike ?", "%#{params[:query]}%")
   end

   def show
   end

   def edit

   end

   def note_params
     params.require(:notepad).permit!
   end

   def update
     if  @note.update(note_params)
       redirect_to folder_note_path
     else
       render :edit
     end
   end

   def new
     @folder = current_user.folders.find(params[:folder_id])
     @note = @folder.notepads.new
   end

  def destroy
    @note.destroy
    redirect_to folder_notes_path
  end

   def create
     @folder = current_user.folders.find(params[:folder_id])
     @note = @folder.notepads.new(note_params)
     if @note.save
       redirect_to folder_note_path(params[:folder_id], @note)
     else
       render :new
     end
   end
   private
     # Use callbacks to share common setup or constraints between actions.
     def set_note
       @folder = current_user.folders.find(params[:folder_id])
       @note = @folder.notepads.find(params[:id])
     end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <% if @folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% @folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<% if @folders && @folders.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @folders.each do |folder| %>
        <tr>
          <td><%= folder.name %></td>
          <td><img src="<%= folder.image_url %>" width="30px" height="30px"/></td>
          <td><%= folder.desc %></td>        <td><%= link_to 'Show', folder %></td>
          <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
          <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure you want to delete this folder?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= paginate @folders %>
  <br>
  <% if params[:visible] == "true" %>
    <a href="/?visible=false">Show Hidden</a>
  <% else %>
    <a href="/?visible=true">Show Visible</a>
  <% end %>

  | <%= link_to 'New Folder', new_folder_path %>
<% else %>
  <p>You have no folders.</p>
  <%= link_to 'Make a new Folder', new_folder_path, class: "btn btn-danger" %>
<% end %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form' %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @folder.image_url %>" width="50px"/>
</p>

<p>
  <strong>Desc:</strong>
  <%= @folder.desc %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @folder.visible %>
</p>
<% if @notes && @notes.any? %>
<p>
  <strong><%= link_to 'Notes:', folder_notes_path(params[:id]) %></strong>
  <ul><% @folder.notepads.each do |note| %>
    <li><%= link_to note.text, folder_note_path(@folder, note) %></li>
  <% end %></ul>
</p>
<% else %>
<p> You have no notes! </p>
<%= link_to 'Make a note', new_folder_note_path(params[:id]), class: "btn btn-danger" %><br>
<% end %>
Created <%= time_ago_in_words(@folder.created_at) %> ago
<br>
<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a class="title text-danger" href="/">Notes</a>
<span style="margin-left: 50%">
  <% if user_signed_in? %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
  <% else %>
    <span>
      <%= link_to 'Log in', new_user_session_path, class:"btn btn-danger" %>
      <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-danger" %>
    </span>
  <% end %>
</span>
<%= yield %>

</body>
</html>

app/views/notes/edit.html.erb
<%#= form_for @note, url: notepad_path(@note) do |f| %>
<ul><% @note.errors.full_messages.each do |error| %>
 <li><%= error %></li>
<% end %></ul>
<%= form_for @note, :url => folder_note_path do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :text, class: "form-control" %><br>
  </div>
  <%= f.label :url %>
  <%= f.text_field :url %><br>
  <%= f.submit class:"btn btn-danger" %>
<% end %>

app/views/notes/index.html.erb
 <table class="table table-striped" style="width: 300px">
  <tr>
    <td>Title</td>
    <td>Text</td>
    <td></td>
    <td></td>
  </tr>
  <% @notes.each do |note| %>
  <tr>
    <td>Note</td>
    <td><%= note.text %></td>
    <td><%= link_to "View Note", folder_note_path(params[:folder_id], note), class: "btn btn-danger" %></td>
    <td><%= link_to 'Delete', folder_note_path(params[:folder_id], note), method: :delete, data: { confirm: "Are you sure you want to delete this note?"}, class: "btn btn-danger" %></td>

  </tr>
  <% end %>

</table>
<%= link_to "Back to Folder", folder_path(params[:folder_id]), class: "btn btn-danger" %>
<%= link_to "New Note", new_folder_note_path, class: "btn btn-danger" %>
<%= link_to "Search Notes", search_notepad_path, class: "btn btn-danger" %>

app/views/notes/new.html.erb
<%#= form_for @note, url: notepad_path(@note) do |f| %>

 <ul><% @note.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %></ul>
 <%= form_for @note, :url => new_folder_note_path do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :text, class: "form-control" %><br>
  </div>
  <div class="form-group">
  <%= f.label :url %>
  <%= f.text_field :url %><br>
</div>
  <%= f.submit class:"btn btn-danger" %>
<% end %>

app/views/notes/search.html.erb
<%= form_tag do %>
<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
 <%= text_field_tag :query %>
 <%= submit_tag "Search", class: "btn btn-danger" %>
<% end %>

app/views/notes/searchbutton.html.erb
<h2>Search Results</h2>
<table class="table table-striped" style="width: 300px">
  <tr>
    <td>Title</td>
    <td>Text</td>
    <td></td>
  </tr>
  <% @search.each do |search| %>
    <tr>
      <td>Note</td>
      <td><%= search.text %></td>
      <td><%= link_to "View Note", folder_note_path(params[:folder_id], search), class: "btn btn-danger" %></td>
    </tr>
  <% end %>
</table>

app/views/notes/searchresult.html.erb
<%= @search %>

app/views/notes/show.html.erb
<!-- <a class="btn btn-danger" href="/notes/<%= @note.id %>/edit">Edit</a> -->

<table class="table table-striped" style="width: 300px">
  <tr>
    <td><%= @folder.name %></td>
    <td>Note</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><%= @note.text %></td>
    <td><%= link_to "Edit", edit_folder_note_path, class: "btn btn-danger" %></td>
  </tr>
</table>
<%= link_to "All Notes", folder_notes_path, class: "btn btn-danger" %>